<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\tModLoader.targets" />
  <PropertyGroup>
    <AssemblyName>deeprockitems</AssemblyName>
    <TargetFramework>net8.0</TargetFramework>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <LangVersion>latest</LangVersion>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>
  <ItemGroup>
	  <Reference Remove="System.Drawing" />
    <None Remove="Assets\CooldownUIBackground.png" />
    <None Remove="Assets\MollyPetOutline.png" />
    <None Remove="Assets\Tiles\SludgeTiles.png" />
    <None Remove="Assets\UI\UpgradeStationHover.png" />
    <None Remove="Assets\Upgrades\Overclocks\Backgrounds.png" />
    <None Remove="Assets\Upgrades\Overclocks\Clean.png" />
    <None Remove="Content\Buffs\Irradiated.png" />
    <None Remove="Content\Buffs\Sludge.png" />
    <None Remove="Content\Projectiles\CryoCannonProjectiles\IceSpear.png" />
  </ItemGroup>
  <ItemGroup>
	<PackageReference Include="AssGen" OutputItemType="Analyzer" ReferenceOutputAssembly="false" Version="2.0.0" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Common\NPCs\" />
  </ItemGroup>
</Project>